### ISSUE TITLE
i cannot see any anime link from another country

### ISSUE THREAD

**Issue by Dokman** [alzamer2/Crunchyroll-XML-Decoder#1]
How i can see the other anime in for example USA like the proxy, because i am from spain and i can only watch the spanish registered anime :(

**Comment by alzamer2** [comment]
try using auto cash option ( number 5), i updated it so it can cash them even if the anime is usa locked

you need go to setting (option number 7) and select USA proxy (option number 5) to download though

**Comment by alzamer2** [comment]
i will close this issue if no new replay come whiten 48hr

**Comment by Dokman** [comment]
sorry hahaha i will test now

**Comment by Dokman** [comment]
![image](https://cloud.githubusercontent.com/assets/2290904/25107859/3e51d98a-23d2-11e7-8e35-19d2325fe9a3.png)
This is an example, and for example the second season i don't know how to get the link

**Comment by Dokman** [comment]
Why only have the 3 last episodes? :(

PS:
I was busy at the real life sorry... :(

**Comment by alzamer2** [comment]
damn crunchyroll did halfed a** job
they created rss page for only the 2nd series so it did not check the other methhod
i will modify the code later
for now open crunchy-xml-decoder.py with any text editor (like notepad) 
then replace it with this file
[crunchy-xml-decoder.py.txt](https://github.com/alzamer2/Crunchyroll-XML-Decoder/files/930267/crunchy-xml-decoder.py.txt)
ps remove the txt from the name and try it out

**Comment by alzamer2** [comment]
i updated the code
ok i tried to fix the problem on the code

**Comment by Dokman** [comment]
![image](https://cloud.githubusercontent.com/assets/2290904/25173703/6ba5aa8c-24f5-11e7-9f04-0dcb82b7eab2.png)

PS: it open me a notepad automatically why? :(

**Comment by Dokman** [comment]
another thing, this numbers are not the real MB of the files so can you try to set it to MB?

**Comment by alzamer2** [comment]
the notpad open so that you can hash or delete any link that you already downloaded other wise every time you autocash you will begin from the first episode
as well for that number its indecate the segement of the video and Crunchyroll is the one he make it so i cant change it, and the code display it to show progress

i will try what i can but cant promise you any thing

**Comment by Dokman** [comment]
okay hahaha have you seen the second issue that i've opened?

**Comment by alzamer2** [comment]
check the code now i updated the code to show size and download speed

**Comment by Dokman** [comment]
okay let me 2 hours and i will test it and thank you so much <3
