### ISSUE TITLE
Problem when downloading

### ISSUE THREAD

**Issue by Riggola** [alzamer2/Crunchyroll-XML-Decoder#10]
Hello, im trying with your fork version but i still get this error

https://pastebin.com/4B2U5NzR

Can you help ?

**Comment by alzamer2** [comment]
this is premium epissode, it ill become free at Jul 27, 2017 (you can see when it will become free at right side under title)
from what you post i see that you loged in as guest

**Comment by Riggola** [comment]
this is the same thing i was thinking, thank you for confirmed it, for now i can close
