### ISSUE TITLE
USA Proxy: Languages not work

### ISSUE THREAD

**Issue by Dokman** [alzamer2/Crunchyroll-XML-Decoder#2]
When i try to download the anime it only download with English and not other languages

**Comment by alzamer2** [comment]
the defult subtitle is english 
 i checked attack on titain it only have 1 subtitle is there

**Comment by Dokman** [comment]
ah okay it can be posible hahaha but i have in my setup spanish to default language so...
it was a mindfuck for me you know what i mean?
