### ISSUE TITLE
Settings crash

### ISSUE THREAD

**Issue by Dokman** [alzamer2/Crunchyroll-XML-Decoder#3]
![image](https://cloud.githubusercontent.com/assets/2290904/25199094/f12c044a-2549-11e7-9eb3-4e3292da6549.png)

**Comment by alzamer2** [comment]
I medified settings you need to delete old settings.ini

**Comment by Dokman** [comment]
![image](https://cloud.githubusercontent.com/assets/2290904/25207242/5f2be3fc-256d-11e7-845c-eeb0bd71528b.png)

**Comment by alzamer2** [comment]
to tell you the truth i have no idea, i ran he code multi time and did not see any problem

try to download fresh copy from the lastes code and try again

if it did not work post it here with the link that you tried

**Comment by alzamer2** [comment]
i let someone else test the new code and he downloaded 1 episode with 1.34 GB at speed 27Mbps
so maybe the peoblem is in the link are some old file mixing with the new code

**Comment by Dokman** [comment]
okay i need one hour and i wil test it :)

**Comment by Dokman** [comment]
sorry when i arrive home i will test it

**Comment by Dokman** [comment]
Closing all working right now

**Comment by alzamer2** [comment]
so every thing worked out at end?
